### PR TITLE
Add devcontainer support

### PR DESCRIPTION
**Pull request by electrocucaracha**
This feature enables customizes the [codespaces](https://github.com/features/codespaces) creation installing the dependencies required for the project.

### CODE REVIEW

**Comment by fmoctezuma** [comment]
I was able to test your PR in github codespaces and is working fine, just have a couple of comments

To be able to load the images I needed to run hugo as follows:
```
$ hugo server --baseURL="https://${CODESPACE_NAME}-1313.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}" --appendPort=false
```
Are you using a different more simplistic way to properly load the images? I'm probably overthinking since this is my first time using codespaces.

Would be also great if you add this as a contribution guide for new members.
I'm not sure if opensource projects are adopting gh codespaces, but In my opinion it works fine and speed up contribution, and it won't hurt, I'll let the admins to decide if they want to go this route.

-Francisco

**Comment by alsotoes** [comment]
About the [subscription](https://github.com/features/codespaces#:~:text=Get%20up%20to%2060%20hours%20free%20each%20month) thing, it seems to be free for 60 hrs/month while using 2 CPUs, which is more than enough for this project.

On the other hand, it looks like a good idea to add codespaces, Netlify, and Dockerfile support for this project, but we need an issue to track these key things, like how to run it on codespaces.

**Comment by electrocucaracha** [comment]
> I was able to test your PR in github codespaces and is working fine, just have a couple of comments
> 
> To be able to load the images I needed to run hugo as follows:
> 
> ```
> $ hugo server --baseURL="https://${CODESPACE_NAME}-1313.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}" --appendPort=false
> ```
> 
> Are you using a different more simplistic way to properly load the images? I'm probably overthinking since this is my first time using codespaces and hugo.
> 
> Would be also great if you add this as a contribution guide for new members. I'm not sure if opensource projects are adopting gh codespaces, but In my opinion it works fine and speed up contribution, and it won't hurt, I'll let the admins to decide if they want to go this route.
> 
> -Francisco

For some reason, when I request the creation of the codespaces from my side, the creation keeps waiting for connection. Anyway, ideally after the post-command execution the developer should run `hugo server` in the terminal and GitHub should autodetect the ports. It's possible to make those ports [public](https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace#sharing-a-port).

Regarding the costs, I think those hours are enough for running a demo and testing the functionality, even better that are quotes per user, and we don't have control over them, at least for the Free edition.

**Comment by alsotoes** [comment]
Hey @electrocucaracha testing the run command that @fmoctezuma described [here: pull/26#issuecomment-1817311710](https://github.com/opensource-latinamerica/openinframx/pull/26#issuecomment-1817311710) The main issue is that the site will be redirected to the codespaces url, but the images will run at http://localhost:1313 and none of them will be displayed in the testing url.

But that will be something to add to the post about how to use codespaces to develop and test the site.
- Alvaro

**Review by alsotoes — APPROVED** [review]
/lgtm

**Pull request merged**
